
services:
  backend:
    container_name: blabber_backend
    image: blabber_backend
    restart: always
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
  
  redis:
    container_name: blabber_redis
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data

  frontend: 
    container_name: blabber_frontend
    image: blabber_frontend
    restart: always
    build:
      context: .
      dockerfile: ./compose/dev/node/Dockerfile
    volumes:
      - ./front/web/:/app
      - /app/node_modules
    ports:
      - 5173:5173

volumes:
  redis-data:
