# Generated by Django 5.1.7 on 2025-03-13 17:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabbery', '0002_remove_user_unique_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseChat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Room UUID')),
                ('limit', models.IntegerField(default=2, verbose_name='Limit')),
            ],
            options={
                'verbose_name': 'Base Room',
                'verbose_name_plural': 'Base Rooms',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Message UUID')),
                ('content', models.TextField(verbose_name='Content')),
                ('timestamp', models.DateField(auto_now_add=True, verbose_name='Timestamp')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='blabbery.basechat', verbose_name='Chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='DirectChat',
            fields=[
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='direct_chat', serialize=False, to='blabbery.basechat')),
                ('online', models.ManyToManyField(blank=True, related_name='direct_chat_online', to=settings.AUTH_USER_MODEL, verbose_name='Online')),
                ('users', models.ManyToManyField(blank=True, related_name='direct_chat', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Direct Chat',
                'verbose_name_plural': 'Direct Chats',
            },
            bases=('blabbery.basechat',),
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='group_chat', serialize=False, to='blabbery.basechat')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('rules', models.TextField(blank=True, verbose_name='Rules')),
                ('code', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Invite Code')),
                ('online', models.ManyToManyField(blank=True, related_name='group_chat_online', to=settings.AUTH_USER_MODEL, verbose_name='Online')),
                ('staff', models.ManyToManyField(blank=True, related_name='group_chat_staff', to=settings.AUTH_USER_MODEL, verbose_name='Staff')),
                ('users', models.ManyToManyField(blank=True, related_name='group_chat', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Group Chat',
                'verbose_name_plural': 'Group Chats',
            },
            bases=('blabbery.basechat',),
        ),
    ]
