# Generated by Django 5.1.7 on 2025-03-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabbery', '0003_basechat_message_directchat_groupchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='basechat',
            name='limit',
            field=models.IntegerField(blank=True, default=2, verbose_name='Limit'),
        ),
    ]
