# Generated by Django 5.1.7 on 2025-03-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabbery', '0004_groupchat_public_alter_basechat_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='code',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Invite Code'),
        ),
    ]
